/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LiveRouteImport } from './routes/live'
import { Route as ReactRouteImport } from './routes/react'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ShareRouteImport } from './routes/share'
import { Route as TestSessionIdRouteImport } from './routes/test/$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ReactRoute = ReactRouteImport.update({
  id: '/react',
  path: '/react',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const TestSessionIdRoute = TestSessionIdRouteImport.update({
  id: '/test/$sessionId',
  path: '/test/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/live': typeof LiveRoute
  '/react': typeof ReactRoute
  '/sessions': typeof SessionsRoute
  '/setup': typeof SetupRoute
  '/share': typeof ShareRoute
  '/test/$sessionId': typeof TestSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/live': typeof LiveRoute
  '/react': typeof ReactRoute
  '/sessions': typeof SessionsRoute
  '/setup': typeof SetupRoute
  '/share': typeof ShareRoute
  '/test/$sessionId': typeof TestSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/live': typeof LiveRoute
  '/react': typeof ReactRoute
  '/sessions': typeof SessionsRoute
  '/setup': typeof SetupRoute
  '/share': typeof ShareRoute
  '/test/$sessionId': typeof TestSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/live'
    | '/react'
    | '/sessions'
    | '/setup'
    | '/share'
    | '/test/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/live'
    | '/react'
    | '/sessions'
    | '/setup'
    | '/share'
    | '/test/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/live'
    | '/react'
    | '/sessions'
    | '/setup'
    | '/share'
    | '/test/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LiveRoute: typeof LiveRoute
  ReactRoute: typeof ReactRoute
  SessionsRoute: typeof SessionsRoute
  SetupRoute: typeof SetupRoute
  ShareRoute: typeof ShareRoute
  TestSessionIdRoute: typeof TestSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/react': {
      id: '/react'
      path: '/react'
      fullPath: '/react'
      preLoaderRoute: typeof ReactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$sessionId': {
      id: '/test/$sessionId'
      path: '/test/$sessionId'
      fullPath: '/test/$sessionId'
      preLoaderRoute: typeof TestSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LiveRoute: LiveRoute,
  ReactRoute: ReactRoute,
  SessionsRoute: SessionsRoute,
  SetupRoute: SetupRoute,
  ShareRoute: ShareRoute,
  TestSessionIdRoute: TestSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
